version: "3.9"  # Or a more recent version if you prefer
services:
  dind:
    container_name: dind
    image: kasmweb/ubuntu-focal-dind:1.16.0
#    volumes:
#      - UserProfile_dind:/home/kasm-user
    ports:
      - 6901:6901
    environment:
      - VNC_PW=pl123456
      
    shm_size: "512m" # Important for shared memory

#volumes:
#  UserProfile_dind: {}
  
