version: "3.9"  
services:
  tor:
    container_name: tor
    image: kasmweb/tor-browser:1.16.0
    volumes:
      - UserProfile_Tor:/home/kasm-user
    ports:
      - 6901:6901
    environment:
      - VNC_PW=pl123456
      
    shm_size: "512m" # Important for shared memory

volumes:
  UserProfile_Tor: {}
  
