version: "3.9"  # Or a more recent version if you prefer
services:
  chrome:
    container_name: chrome
    image: kasmweb/chrome:1.16.0
    volumes:
      - UserProfile_Chrome:/home/kasm-user
    ports:
      - 6901:6901
    environment:
      - VNC_PW=pl123456
      
    shm_size: "512m" # Important for shared memory

volumes:
  UserProfile_Chrome: {}
  
