version: "3.9"  # Or a more recent version if you prefer
services:
  ubuntu-focal:
    container_name: ubuntu-focal
    image: kasmweb/ubuntu-focal-desktop:1.16.0
    volumes:
      - UserProfile_ubuntu-focal:/home/kasm-user
    ports:
      - 6901:6901
    environment:
      - VNC_PW=pl123456
      
    shm_size: "512m" # Important for shared memory

#volumes:
#  UserProfile_dind: {}
  
