version: "3.9"  
services:
  brave:
    container_name: brave
    image: kasmweb/brave:1.16.0
    volumes:
      - UserProfile_brave:/home/kasm-user
    ports:
      - 6901:6901
    environment:
      - VNC_PW=pl123456
      
    shm_size: "512m" # Important for shared memory

volumes:
  UserProfile_brave: {}
  
